using System.Drawing;
using System.Reflection;
using System.Windows.Forms;

namespace LaTeXSquiggly.App.Platform;

/// <summary>
/// The tray mark, from the same artwork the Mac app is built from.
///
/// The icons are real multi-resolution .ico files, generated by
/// Tools/make_windows_icons.py, rather than drawn here at run time. Two reasons.
/// The source artwork is a mark floating in a large transparent canvas, only 12
/// per cent of which is ink, so anything that hands the raw PNG to a 32 pixel
/// icon draws a mark about nine pixels wide surrounded by nothing. And a tray
/// asks for whichever size suits the display it is on, so shipping 16 through
/// 256 lets Windows pick one rather than shrink one.
///
/// Two states, not three. The icon answers "is it converting right now", which
/// is the same answer whether the app is switched off or merely staying quiet in
/// TeXstudio; the menu answers "why not". macOS gets to hand a template image to
/// the system and have it coloured to suit the menu bar. Windows draws a tray
/// icon exactly as given, so the mark carries its own orange, which reads on a
/// light taskbar and a dark one.
/// </summary>
internal static class AppIcon
{
    private static Icon? _active;
    private static Icon? _inactive;
    private static Icon? _window;

    /// <summary>Sized for the tray of whichever display the taskbar is on.</summary>
    public static Icon Tray(bool active)
    {
        _active ??= Sized(Load("tray-active.ico"));
        _inactive ??= Sized(Load("tray-inactive.ico"));
        return active ? _active : _inactive;
    }

    /// <summary>The full app mark, for the settings window and the taskbar.</summary>
    public static Icon Window => _window ??= Load("app.ico");

    private static Icon Sized(Icon source)
    {
        try
        {
            // Picks the closest entry rather than scaling the largest, which is
            // the difference between a crisp 16 pixel mark and a blurred one.
            var sized = new Icon(source, SystemInformation.SmallIconSize);
            source.Dispose();
            return sized;
        }
        catch (Exception)
        {
            return source;
        }
    }

    private static Icon Load(string name)
    {
        var assembly = Assembly.GetExecutingAssembly();
        using var stream = assembly.GetManifestResourceStream(name);
        if (stream is null)
        {
            // Missing artwork is a packaging fault, not a reason to run with no
            // tray icon at all: an app with no mark cannot be switched off.
            return SystemIcons.Application;
        }
        try { return new Icon(stream); }
        catch (Exception) { return SystemIcons.Application; }
    }
}
