// Generated by Tools/generate_tables.py — do not edit by hand.
//
// Every character below is resolved from its official Unicode name via
// Python's unicodedata.lookup, not transcribed from memory. Re-run the
// generator to change this file.

public enum ScriptTables {

    /// Characters that have a Unicode superscript form.
    /// Complete for digits; every lowercase letter except `q`.
    public static let superscripts: [Character: Character] = [
        "0": "⁰",    // U+2070 SUPERSCRIPT ZERO
        "1": "¹",    // U+00B9 SUPERSCRIPT ONE
        "2": "²",    // U+00B2 SUPERSCRIPT TWO
        "3": "³",    // U+00B3 SUPERSCRIPT THREE
        "4": "⁴",    // U+2074 SUPERSCRIPT FOUR
        "5": "⁵",    // U+2075 SUPERSCRIPT FIVE
        "6": "⁶",    // U+2076 SUPERSCRIPT SIX
        "7": "⁷",    // U+2077 SUPERSCRIPT SEVEN
        "8": "⁸",    // U+2078 SUPERSCRIPT EIGHT
        "9": "⁹",    // U+2079 SUPERSCRIPT NINE
        "+": "⁺",    // U+207A SUPERSCRIPT PLUS SIGN
        "-": "⁻",    // U+207B SUPERSCRIPT MINUS
        "=": "⁼",    // U+207C SUPERSCRIPT EQUALS SIGN
        "(": "⁽",    // U+207D SUPERSCRIPT LEFT PARENTHESIS
        ")": "⁾",    // U+207E SUPERSCRIPT RIGHT PARENTHESIS
        "a": "ᵃ",    // U+1D43 MODIFIER LETTER SMALL A
        "b": "ᵇ",    // U+1D47 MODIFIER LETTER SMALL B
        "c": "ᶜ",    // U+1D9C MODIFIER LETTER SMALL C
        "d": "ᵈ",    // U+1D48 MODIFIER LETTER SMALL D
        "e": "ᵉ",    // U+1D49 MODIFIER LETTER SMALL E
        "f": "ᶠ",    // U+1DA0 MODIFIER LETTER SMALL F
        "g": "ᵍ",    // U+1D4D MODIFIER LETTER SMALL G
        "h": "ʰ",    // U+02B0 MODIFIER LETTER SMALL H
        "i": "ⁱ",    // U+2071 SUPERSCRIPT LATIN SMALL LETTER I
        "j": "ʲ",    // U+02B2 MODIFIER LETTER SMALL J
        "k": "ᵏ",    // U+1D4F MODIFIER LETTER SMALL K
        "l": "ˡ",    // U+02E1 MODIFIER LETTER SMALL L
        "m": "ᵐ",    // U+1D50 MODIFIER LETTER SMALL M
        "n": "ⁿ",    // U+207F SUPERSCRIPT LATIN SMALL LETTER N
        "o": "ᵒ",    // U+1D52 MODIFIER LETTER SMALL O
        "p": "ᵖ",    // U+1D56 MODIFIER LETTER SMALL P
        "r": "ʳ",    // U+02B3 MODIFIER LETTER SMALL R
        "s": "ˢ",    // U+02E2 MODIFIER LETTER SMALL S
        "t": "ᵗ",    // U+1D57 MODIFIER LETTER SMALL T
        "u": "ᵘ",    // U+1D58 MODIFIER LETTER SMALL U
        "v": "ᵛ",    // U+1D5B MODIFIER LETTER SMALL V
        "w": "ʷ",    // U+02B7 MODIFIER LETTER SMALL W
        "x": "ˣ",    // U+02E3 MODIFIER LETTER SMALL X
        "y": "ʸ",    // U+02B8 MODIFIER LETTER SMALL Y
        "z": "ᶻ",    // U+1DBB MODIFIER LETTER SMALL Z
    ]

    /// Characters that have a Unicode subscript form.
    /// Complete for digits; letters only `a e h i j k l m n o p r s t u v x`.
    /// Missing: `b c d f g q w y z` — these must return `.unsupported`.
    public static let subscripts: [Character: Character] = [
        "0": "₀",    // U+2080 SUBSCRIPT ZERO
        "1": "₁",    // U+2081 SUBSCRIPT ONE
        "2": "₂",    // U+2082 SUBSCRIPT TWO
        "3": "₃",    // U+2083 SUBSCRIPT THREE
        "4": "₄",    // U+2084 SUBSCRIPT FOUR
        "5": "₅",    // U+2085 SUBSCRIPT FIVE
        "6": "₆",    // U+2086 SUBSCRIPT SIX
        "7": "₇",    // U+2087 SUBSCRIPT SEVEN
        "8": "₈",    // U+2088 SUBSCRIPT EIGHT
        "9": "₉",    // U+2089 SUBSCRIPT NINE
        "+": "₊",    // U+208A SUBSCRIPT PLUS SIGN
        "-": "₋",    // U+208B SUBSCRIPT MINUS
        "=": "₌",    // U+208C SUBSCRIPT EQUALS SIGN
        "(": "₍",    // U+208D SUBSCRIPT LEFT PARENTHESIS
        ")": "₎",    // U+208E SUBSCRIPT RIGHT PARENTHESIS
        "a": "ₐ",    // U+2090 LATIN SUBSCRIPT SMALL LETTER A
        "e": "ₑ",    // U+2091 LATIN SUBSCRIPT SMALL LETTER E
        "h": "ₕ",    // U+2095 LATIN SUBSCRIPT SMALL LETTER H
        "i": "ᵢ",    // U+1D62 LATIN SUBSCRIPT SMALL LETTER I
        "j": "ⱼ",    // U+2C7C LATIN SUBSCRIPT SMALL LETTER J
        "k": "ₖ",    // U+2096 LATIN SUBSCRIPT SMALL LETTER K
        "l": "ₗ",    // U+2097 LATIN SUBSCRIPT SMALL LETTER L
        "m": "ₘ",    // U+2098 LATIN SUBSCRIPT SMALL LETTER M
        "n": "ₙ",    // U+2099 LATIN SUBSCRIPT SMALL LETTER N
        "o": "ₒ",    // U+2092 LATIN SUBSCRIPT SMALL LETTER O
        "p": "ₚ",    // U+209A LATIN SUBSCRIPT SMALL LETTER P
        "r": "ᵣ",    // U+1D63 LATIN SUBSCRIPT SMALL LETTER R
        "s": "ₛ",    // U+209B LATIN SUBSCRIPT SMALL LETTER S
        "t": "ₜ",    // U+209C LATIN SUBSCRIPT SMALL LETTER T
        "u": "ᵤ",    // U+1D64 LATIN SUBSCRIPT SMALL LETTER U
        "v": "ᵥ",    // U+1D65 LATIN SUBSCRIPT SMALL LETTER V
        "x": "ₓ",    // U+2093 LATIN SUBSCRIPT SMALL LETTER X
    ]

    /// Radical signs by index. Only these three exist as single characters.
    public static let radicals: [Int: Character] = [
        2:  "√",    // U+221A SQUARE ROOT
        3:  "∛",    // U+221B CUBE ROOT
        4:  "∜",    // U+221C FOURTH ROOT
    ]
}
