// Generated by Tools/generate_tables.py — do not edit by hand.
//
// Every character below is resolved from its official Unicode name via
// Python's unicodedata.lookup, not transcribed from memory. Re-run the
// generator to change this file.

public enum SymbolTable {

    /// LaTeX command name (without the leading backslash) to its Unicode form.
    public static let symbols: [String: String] = [
        // MARK: Greek, lower case
        "alpha":      "α",    // U+03B1 GREEK SMALL LETTER ALPHA
        "beta":       "β",    // U+03B2 GREEK SMALL LETTER BETA
        "gamma":      "γ",    // U+03B3 GREEK SMALL LETTER GAMMA
        "delta":      "δ",    // U+03B4 GREEK SMALL LETTER DELTA
        "epsilon":    "ϵ",    // U+03F5 GREEK LUNATE EPSILON SYMBOL
        "varepsilon": "ε",    // U+03B5 GREEK SMALL LETTER EPSILON
        "zeta":       "ζ",    // U+03B6 GREEK SMALL LETTER ZETA
        "eta":        "η",    // U+03B7 GREEK SMALL LETTER ETA
        "theta":      "θ",    // U+03B8 GREEK SMALL LETTER THETA
        "vartheta":   "ϑ",    // U+03D1 GREEK THETA SYMBOL
        "iota":       "ι",    // U+03B9 GREEK SMALL LETTER IOTA
        "kappa":      "κ",    // U+03BA GREEK SMALL LETTER KAPPA
        "lambda":     "λ",    // U+03BB GREEK SMALL LETTER LAMDA
        "mu":         "μ",    // U+03BC GREEK SMALL LETTER MU
        "nu":         "ν",    // U+03BD GREEK SMALL LETTER NU
        "xi":         "ξ",    // U+03BE GREEK SMALL LETTER XI
        "omicron":    "ο",    // U+03BF GREEK SMALL LETTER OMICRON
        "pi":         "π",    // U+03C0 GREEK SMALL LETTER PI
        "varpi":      "ϖ",    // U+03D6 GREEK PI SYMBOL
        "rho":        "ρ",    // U+03C1 GREEK SMALL LETTER RHO
        "varrho":     "ϱ",    // U+03F1 GREEK RHO SYMBOL
        "sigma":      "σ",    // U+03C3 GREEK SMALL LETTER SIGMA
        "varsigma":   "ς",    // U+03C2 GREEK SMALL LETTER FINAL SIGMA
        "tau":        "τ",    // U+03C4 GREEK SMALL LETTER TAU
        "upsilon":    "υ",    // U+03C5 GREEK SMALL LETTER UPSILON
        "phi":        "ϕ",    // U+03D5 GREEK PHI SYMBOL
        "varphi":     "φ",    // U+03C6 GREEK SMALL LETTER PHI
        "chi":        "χ",    // U+03C7 GREEK SMALL LETTER CHI
        "psi":        "ψ",    // U+03C8 GREEK SMALL LETTER PSI
        "omega":      "ω",    // U+03C9 GREEK SMALL LETTER OMEGA

        // MARK: Greek, upper case
        "Gamma":   "Γ",    // U+0393 GREEK CAPITAL LETTER GAMMA
        "Delta":   "Δ",    // U+0394 GREEK CAPITAL LETTER DELTA
        "Theta":   "Θ",    // U+0398 GREEK CAPITAL LETTER THETA
        "Lambda":  "Λ",    // U+039B GREEK CAPITAL LETTER LAMDA
        "Xi":      "Ξ",    // U+039E GREEK CAPITAL LETTER XI
        "Pi":      "Π",    // U+03A0 GREEK CAPITAL LETTER PI
        "Sigma":   "Σ",    // U+03A3 GREEK CAPITAL LETTER SIGMA
        "Upsilon": "Υ",    // U+03A5 GREEK CAPITAL LETTER UPSILON
        "Phi":     "Φ",    // U+03A6 GREEK CAPITAL LETTER PHI
        "Psi":     "Ψ",    // U+03A8 GREEK CAPITAL LETTER PSI
        "Omega":   "Ω",    // U+03A9 GREEK CAPITAL LETTER OMEGA

        // MARK: Operators
        "int":       "∫",    // U+222B INTEGRAL
        "iint":      "∬",    // U+222C DOUBLE INTEGRAL
        "iiint":     "∭",    // U+222D TRIPLE INTEGRAL
        "oint":      "∮",    // U+222E CONTOUR INTEGRAL
        "sum":       "∑",    // U+2211 N-ARY SUMMATION
        "prod":      "∏",    // U+220F N-ARY PRODUCT
        "coprod":    "∐",    // U+2210 N-ARY COPRODUCT
        "bigcup":    "⋃",    // U+22C3 N-ARY UNION
        "bigcap":    "⋂",    // U+22C2 N-ARY INTERSECTION
        "bigoplus":  "⨁",    // U+2A01 N-ARY CIRCLED PLUS OPERATOR
        "bigotimes": "⨂",    // U+2A02 N-ARY CIRCLED TIMES OPERATOR
        "bigvee":    "⋁",    // U+22C1 N-ARY LOGICAL OR
        "bigwedge":  "⋀",    // U+22C0 N-ARY LOGICAL AND
        "pm":        "±",    // U+00B1 PLUS-MINUS SIGN
        "mp":        "∓",    // U+2213 MINUS-OR-PLUS SIGN
        "times":     "×",    // U+00D7 MULTIPLICATION SIGN
        "div":       "÷",    // U+00F7 DIVISION SIGN
        "cdot":      "⋅",    // U+22C5 DOT OPERATOR
        "circ":      "∘",    // U+2218 RING OPERATOR
        "bullet":    "∙",    // U+2219 BULLET OPERATOR
        "ast":       "∗",    // U+2217 ASTERISK OPERATOR
        "star":      "⋆",    // U+22C6 STAR OPERATOR
        "oplus":     "⊕",    // U+2295 CIRCLED PLUS
        "ominus":    "⊖",    // U+2296 CIRCLED MINUS
        "otimes":    "⊗",    // U+2297 CIRCLED TIMES
        "oslash":    "⊘",    // U+2298 CIRCLED DIVISION SLASH
        "odot":      "⊙",    // U+2299 CIRCLED DOT OPERATOR
        "infty":     "∞",    // U+221E INFINITY
        "partial":   "∂",    // U+2202 PARTIAL DIFFERENTIAL
        "nabla":     "∇",    // U+2207 NABLA
        "surd":      "√",    // U+221A SQUARE ROOT
        "prime":     "′",    // U+2032 PRIME
        "degree":    "°",    // U+00B0 DEGREE SIGN

        // MARK: Relations
        "leq":       "≤",    // U+2264 LESS-THAN OR EQUAL TO
        "le":        "≤",    // U+2264 LESS-THAN OR EQUAL TO
        "geq":       "≥",    // U+2265 GREATER-THAN OR EQUAL TO
        "ge":        "≥",    // U+2265 GREATER-THAN OR EQUAL TO
        "neq":       "≠",    // U+2260 NOT EQUAL TO
        "ne":        "≠",    // U+2260 NOT EQUAL TO
        "approx":    "≈",    // U+2248 ALMOST EQUAL TO
        "equiv":     "≡",    // U+2261 IDENTICAL TO
        "sim":       "∼",    // U+223C TILDE OPERATOR
        "simeq":     "≃",    // U+2243 ASYMPTOTICALLY EQUAL TO
        "cong":      "≅",    // U+2245 APPROXIMATELY EQUAL TO
        "propto":    "∝",    // U+221D PROPORTIONAL TO
        "ll":        "≪",    // U+226A MUCH LESS-THAN
        "gg":        "≫",    // U+226B MUCH GREATER-THAN
        "prec":      "≺",    // U+227A PRECEDES
        "succ":      "≻",    // U+227B SUCCEEDS
        "preceq":    "≼",    // U+227C PRECEDES OR EQUAL TO
        "succeq":    "≽",    // U+227D SUCCEEDS OR EQUAL TO
        "perp":      "⊥",    // U+22A5 UP TACK
        "bot":       "⊥",    // U+22A5 UP TACK
        "top":       "⊤",    // U+22A4 DOWN TACK
        "parallel":  "∥",    // U+2225 PARALLEL TO
        "nparallel": "∦",    // U+2226 NOT PARALLEL TO
        "mid":       "∣",    // U+2223 DIVIDES
        "nmid":      "∤",    // U+2224 DOES NOT DIVIDE
        "nless":     "≮",    // U+226E NOT LESS-THAN
        "ngtr":      "≯",    // U+226F NOT GREATER-THAN
        "nleq":      "≰",    // U+2270 NEITHER LESS-THAN NOR EQUAL TO
        "ngeq":      "≱",    // U+2271 NEITHER GREATER-THAN NOR EQUAL TO
        "coloneqq":  "≔",    // U+2254 COLON EQUALS

        // MARK: Set notation
        "in":         "∈",    // U+2208 ELEMENT OF
        "notin":      "∉",    // U+2209 NOT AN ELEMENT OF
        "ni":         "∋",    // U+220B CONTAINS AS MEMBER
        "subset":     "⊂",    // U+2282 SUBSET OF
        "supset":     "⊃",    // U+2283 SUPERSET OF
        "subseteq":   "⊆",    // U+2286 SUBSET OF OR EQUAL TO
        "supseteq":   "⊇",    // U+2287 SUPERSET OF OR EQUAL TO
        "nsubseteq":  "⊈",    // U+2288 NEITHER A SUBSET OF NOR EQUAL TO
        "nsupseteq":  "⊉",    // U+2289 NEITHER A SUPERSET OF NOR EQUAL TO
        "subsetneq":  "⊊",    // U+228A SUBSET OF WITH NOT EQUAL TO
        "supsetneq":  "⊋",    // U+228B SUPERSET OF WITH NOT EQUAL TO
        "cup":        "∪",    // U+222A UNION
        "cap":        "∩",    // U+2229 INTERSECTION
        "uplus":      "⊎",    // U+228E MULTISET UNION
        "sqcup":      "⊔",    // U+2294 SQUARE CUP
        "sqcap":      "⊓",    // U+2293 SQUARE CAP
        "setminus":   "∖",    // U+2216 SET MINUS
        "emptyset":   "∅",    // U+2205 EMPTY SET
        "varnothing": "∅",    // U+2205 EMPTY SET
        "forall":     "∀",    // U+2200 FOR ALL
        "exists":     "∃",    // U+2203 THERE EXISTS
        "nexists":    "∄",    // U+2204 THERE DOES NOT EXIST

        // MARK: Logic
        "land":      "∧",    // U+2227 LOGICAL AND
        "wedge":     "∧",    // U+2227 LOGICAL AND
        "lor":       "∨",    // U+2228 LOGICAL OR
        "vee":       "∨",    // U+2228 LOGICAL OR
        "neg":       "¬",    // U+00AC NOT SIGN
        "lnot":      "¬",    // U+00AC NOT SIGN
        "models":    "⊨",    // U+22A8 TRUE
        "vdash":     "⊢",    // U+22A2 RIGHT TACK
        "dashv":     "⊣",    // U+22A3 LEFT TACK
        "therefore": "∴",    // U+2234 THEREFORE
        "because":   "∵",    // U+2235 BECAUSE

        // MARK: Arrows
        "leftarrow":          "←",    // U+2190 LEFTWARDS ARROW
        "gets":               "←",    // U+2190 LEFTWARDS ARROW
        "rightarrow":         "→",    // U+2192 RIGHTWARDS ARROW
        "to":                 "→",    // U+2192 RIGHTWARDS ARROW
        "uparrow":            "↑",    // U+2191 UPWARDS ARROW
        "downarrow":          "↓",    // U+2193 DOWNWARDS ARROW
        "leftrightarrow":     "↔",    // U+2194 LEFT RIGHT ARROW
        "updownarrow":        "↕",    // U+2195 UP DOWN ARROW
        "nearrow":            "↗",    // U+2197 NORTH EAST ARROW
        "searrow":            "↘",    // U+2198 SOUTH EAST ARROW
        "swarrow":            "↙",    // U+2199 SOUTH WEST ARROW
        "nwarrow":            "↖",    // U+2196 NORTH WEST ARROW
        "mapsto":             "↦",    // U+21A6 RIGHTWARDS ARROW FROM BAR
        "hookleftarrow":      "↩",    // U+21A9 LEFTWARDS ARROW WITH HOOK
        "hookrightarrow":     "↪",    // U+21AA RIGHTWARDS ARROW WITH HOOK
        "rightleftharpoons":  "⇌",    // U+21CC RIGHTWARDS HARPOON OVER LEFTWARDS HARPOON
        "Leftarrow":          "⇐",    // U+21D0 LEFTWARDS DOUBLE ARROW
        "Rightarrow":         "⇒",    // U+21D2 RIGHTWARDS DOUBLE ARROW
        "Uparrow":            "⇑",    // U+21D1 UPWARDS DOUBLE ARROW
        "Downarrow":          "⇓",    // U+21D3 DOWNWARDS DOUBLE ARROW
        "Leftrightarrow":     "⇔",    // U+21D4 LEFT RIGHT DOUBLE ARROW
        "Updownarrow":        "⇕",    // U+21D5 UP DOWN DOUBLE ARROW
        "longleftarrow":      "⟵",    // U+27F5 LONG LEFTWARDS ARROW
        "longrightarrow":     "⟶",    // U+27F6 LONG RIGHTWARDS ARROW
        "longleftrightarrow": "⟷",    // U+27F7 LONG LEFT RIGHT ARROW
        "Longleftarrow":      "⟸",    // U+27F8 LONG LEFTWARDS DOUBLE ARROW
        "Longrightarrow":     "⟹",    // U+27F9 LONG RIGHTWARDS DOUBLE ARROW
        "Longleftrightarrow": "⟺",    // U+27FA LONG LEFT RIGHT DOUBLE ARROW
        "implies":            "⟹",    // U+27F9 LONG RIGHTWARDS DOUBLE ARROW
        "impliedby":          "⟸",    // U+27F8 LONG LEFTWARDS DOUBLE ARROW
        "iff":                "⟺",    // U+27FA LONG LEFT RIGHT DOUBLE ARROW

        // MARK: Blackboard bold
        "R": "ℝ",    // U+211D DOUBLE-STRUCK CAPITAL R
        "Q": "ℚ",    // U+211A DOUBLE-STRUCK CAPITAL Q
        "Z": "ℤ",    // U+2124 DOUBLE-STRUCK CAPITAL Z
        "N": "ℕ",    // U+2115 DOUBLE-STRUCK CAPITAL N
        "C": "ℂ",    // U+2102 DOUBLE-STRUCK CAPITAL C
        "H": "ℍ",    // U+210D DOUBLE-STRUCK CAPITAL H
        "E": "𝔼",    // U+1D53C MATHEMATICAL DOUBLE-STRUCK CAPITAL E
        "F": "𝔽",    // U+1D53D MATHEMATICAL DOUBLE-STRUCK CAPITAL F
        "P": "ℙ",    // U+2119 DOUBLE-STRUCK CAPITAL P

        // MARK: Delimiters
        "langle": "⟨",    // U+27E8 MATHEMATICAL LEFT ANGLE BRACKET
        "rangle": "⟩",    // U+27E9 MATHEMATICAL RIGHT ANGLE BRACKET
        "lfloor": "⌊",    // U+230A LEFT FLOOR
        "rfloor": "⌋",    // U+230B RIGHT FLOOR
        "lceil":  "⌈",    // U+2308 LEFT CEILING
        "rceil":  "⌉",    // U+2309 RIGHT CEILING

        // MARK: Miscellaneous
        "ldots":     "…",    // U+2026 HORIZONTAL ELLIPSIS
        "dots":      "…",    // U+2026 HORIZONTAL ELLIPSIS
        "cdots":     "⋯",    // U+22EF MIDLINE HORIZONTAL ELLIPSIS
        "vdots":     "⋮",    // U+22EE VERTICAL ELLIPSIS
        "ddots":     "⋱",    // U+22F1 DOWN RIGHT DIAGONAL ELLIPSIS
        "ell":       "ℓ",    // U+2113 SCRIPT SMALL L
        "hbar":      "ℏ",    // U+210F PLANCK CONSTANT OVER TWO PI
        "aleph":     "ℵ",    // U+2135 ALEF SYMBOL
        "angle":     "∠",    // U+2220 ANGLE
        "triangle":  "△",    // U+25B3 WHITE UP-POINTING TRIANGLE
        "square":    "□",    // U+25A1 WHITE SQUARE
        "dagger":    "†",    // U+2020 DAGGER
        "ddagger":   "‡",    // U+2021 DOUBLE DAGGER
        "checkmark": "✓",    // U+2713 CHECK MARK
        "Re":        "ℜ",    // U+211C BLACK-LETTER CAPITAL R
        "Im":        "ℑ",    // U+2111 BLACK-LETTER CAPITAL I
        "wp":        "℘",    // U+2118 SCRIPT CAPITAL P
        "imath":     "ı",    // U+0131 LATIN SMALL LETTER DOTLESS I
        "jmath":     "ȷ",    // U+0237 LATIN SMALL LETTER DOTLESS J
    ]
}
