//
// Generated by Tools/make_icons.swift from Assets/menu-icon.png.
// Do not edit by hand; edit the artwork and regenerate.
//
//   Scripts/make-icons.sh
//
import Foundation

enum MenuBarIconData {

    /// The mark trimmed to its bounding box and flattened to a black
    /// silhouette, 72 px tall — four times the point size the status
    /// item draws at, so 1x and 2x displays both get an exact integer
    /// downsample. Colour is discarded on purpose: as a template image
    /// it takes its colour from the menu bar, which is the only way one
    /// file reads correctly on a light bar, a dark bar and a
    /// highlighted status item.
    static let png = Data(base64Encoded: """
        iVBORw0KGgoAAAANSUhEUgAAAD4AAABICAYAAACuukaYAAAAAXNSR0IArs4c
        6QAAADhlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAAqACAAQAAAAB
        AAAAPqADAAQAAAABAAAASAAAAABweR2uAAALnklEQVR4Ad2YfZCVVR3Hw1VJ
        BSVU3mF3Wd4UUJkwXiwQtKzGaWrMnEybIptqpvqzP5qpZnRypv6qmZqxpKZQ
        cpossgkMIQORJGcFDQJ5XZYlQFxeAwnXqM/nzj07h2fvfe7z3L27XfjOfHhe
        7nnOOb/f+f1+5ywD3lWdBvDZVTAWJsL04v1grufgCOyAV2EndMJ/4YJWA7Of
        BF+AFaCRGpXkLO/+Dt+EFrgELlgNZOZzYCmcgqSxpZ6P0+5x0PgLUhq9EF6A
        UgamvXuTb74LV8AFpcuY7Qfgr5BmYLnfzPuNMBMuGJmbN8KfoJxhWd538P1X
        oC6UpeBcy0wfgrt6OWNTZVgv+6jZ55UMd8v6DHyxBiN20ceJGvRTky7SDL+U
        EW4CV3tQDUY7Rh+ba9BPn3cxnBEWw38gSw6ntfkXfSwB06au9W5m9wC4DaUZ
        lOW3f9PHWvgg1LUM/6ngZLMYltbmNH2shnugrvZw8zgpz9v3wezkDzmfzWm3
        wJ/DOvAIW06e/a361xSxqDo3F8EzwDtg5OjIk/AWvA1VK2m4BxUPGYb55VX2
        agTsg6fhSfC87uSTcizrSDM0wRgYBUPBYhoMt8aIhlsrjsIB8FywFRxLh+RS
        bLhed599CJxMNXKCe+DHsAycVCzHcFU9EN1cZCLXcXA9aHADpMmVdls8BFvg
        NdgAOvgY5FYoaP5RkZa35X5zn3YSOm4IJKVRt8N34DnYD35Trr8s73W0BfjP
        8A2YDJdAZrkShpo5mWXAZBsnsB0ehGQRcwWb4OvwPLgqye9r8awjfwAWZu3J
        JPP5o2AIVTMJva7Hk0Zfyrtp4ITaoZq+83xj+H8bTNlMMu++B3kGCW0tOr+D
        kRDLlZ4Cj4EFKbTv6+s6xroTUhXywZWaldqy/I/+D8wSOJhooiM+B5+C90B/
        qZmBWiDYVnJcfzQfrgY/yCuL0zZYk/jQs4Bed1vsT6OdhkVatKusNFycqMbn
        lWG+AdwJghxwPNwPo8PLfrw6p7fAlCori09QqodCo8TVPdX9M5YHk1thTvwy
        w70Ttb8zxbae5MSFyaM2Gsu5tI803AZ6yP88tMjl0Ts09hQV60oebgP37aw6
        ScOXYSO4Q2is3xsxE8D92UpdaXGsM6tgM6RKw/W021g75A1NvzW0Ylkob4pf
        VLg3Tf4Ai8GTmAugXG3/jDVtbgGdeTOMA7ffWM6jA35T5HD8Y6n7EOqeddfD
        3FKNUt65Aq5wkM+ulGfwLDLadoFHXFc8VhcPOsEFeQlcyZmgE5rA6DQyTA8N
        9fsVsBt0RKqC4Ya6HS8CvZxVfj86aqzhrpRVNYtCtO2t0NioMhrcQZ4Ft8oh
        4Hg6qBP+Cf4Rk1sj+GIpOJmsOND3IciJTIaDkKUPV3wr3A0N0G+KBzNkNOR2
        yLq1GWoa+AyEXHe1PwFZwl1HXQn+ZXYWXD3n4bVPFRvuHxqewjxwuB3Fv/FY
        UhpuuLeCuaV8ngXTfMggC5UFazoYLTfAeBgL18EgMH10kk52nr1W0jg9bZi+
        F8Zk7F1DQ40wdJ3ctbAA3NOzyD6GgcZbwHTc+4pX78X37hY6pxEcQ8c7ps5w
        3MxywFh2sBMegylgAakkQ3seOJndYKi+BBtgIeSRq+oKi1EQpFH2q4Pdeo9B
        J3QUaefaVuQQV9MmVckVt7HGe4gw5KSSnKzhqsM2FRu7PZrz7rumTm/lGC6S
        ZwQXw6reAm5tpqXRMAOc72gwEk5BRQfQ5jwZoneBxU5vV0IjfwtxaLtq98Ir
        UOn7Wv3uonkK3A5PwEfAefRQqRW3kXnjcfTDMBwqyRXR+KcgeNnQ7AAjwcEb
        IXYMjzWX8xgI5r8F0ohz7H1ginSrnOE2cJLzYbIPGXSUNkvBPAwKxvuHTDu4
        TV4Hfe0AhiiknwXT8HfcvXAECkoz3KK1APRaJRmqdvpLiA33O8OvE7aBBW8z
        6H3rgnt4XzrBXNfoCWCNMPqOQ+HBayn50VWlfijzTgPLydQ5BptgB6yEEdAM
        RpQT834UWAwNz7RF4edcup7W98EB8I+hk3qhnMyVeEsp1873rrhVNLna/hZL
        B1gwpR1MAZ2roTIYTAXripPVOVZpzxRefWekVCOd+nFwzNXlDPd9E7gSWdRF
        ozY4k6VxsY3O0lHi9qkGgKGvcTredHML0zlGwiR4PywEHZFHRvAMWAAby31o
        XjwKrpATrIRh/FUoJw3SGFdUg6qRoe/3LXA/vAiV5lXq9xV8N6vUiuuZRrgH
        nHAl2bmFbU2JhhYvDxl3gLnsyp2G3WCha4Ww2tymyhoS0uQw92+DEWD455GO
        aylluLlmIWjO2JsT0ICdifaG4udBB5pf9ut4ng8M70/CFlgOFrs3IKt0wGuw
        B/Iabg0ZCefJic0BOywVJqXeudqfhVh2/AgcgrR00QG74FdwN5jPWdVEwzVQ
        ak5p7xzz4eSKD+Hll6ERskij9sNfosb2ORcWgdU5TRo6HnTUVJgPT4GrmbY9
        moIWu7wFjk8KC3EuNtwK+iH4GJjnWeQxdT0ciBqb1wuhRzhFbeJbjfCbaeC2
        ZcQ9W2QrV8eI5dxMw0UwNv4h430X7U4Hw+1sHHwNXPWsMmyeh3h1rNpTQIPy
        yDkMhdkwEVyAzfAPMJ2ccAO4t7ul3QbV7BAn+O5IMNxq+2mYAVllHh0FT2Ox
        NLiaCYU+NG4YWIRuAAuZBdS0Cn0b5nnqAc271cFdu4Y7kB5+EPJM2IlouFtL
        LFdmf/yiynsjYHCRKrvo8Zlz8+S2zc5dbbecJsgjDT8NZxMfGf7mvatUbzJt
        TM3DGm7l9QzryueV4S6xNHgtrIpf1sG9kbkMXgDPEoXVdtWCEVmvFrSNUOoA
        4Q5xB2i87bL22VftPFL/CCaBdaKwyp7SnGRe2YE1YjeYN7H06EEwtI7DNUVC
        MeWx3+RKPwE/gV1gihYmPtqbKuXW9yXw6Plqog/3XyNiHxhiVmiL6CiwYvut
        xcsK7b21xtSrlXS+81oCv4cOKIQ418Ky640HfKhSGvgi/BTWwJuQlAZ5SNE4
        t6HLI3xvuowDQ3E6TAadU40jrDE7YSUsBxfkOBRWmmtBht7p4n21F/N5HjTB
        dvC05cCGmIcF+z8D5rroKLdBr743ry8D+7kaXH2jcCroBCOlEYwMHZaUfZ6E
        /eCB52V4BfZAJ+iIHtLwQz3e5n/hhCaAqzYXPHRYMB3UientgO91hjgxa4GT
        3FG86rjX4W+gIzTY1R8JHmysF0aODjsCoY83ivcWslPQHdbc95CGW5i6QK/3
        ViGEnWw5OeHgDB3jqusEV00naPSmIjqkHZxniAqvPtuP3wcHa4Pv1CAYDjqs
        AYy8A6BTCrIyj4dfw8zCm//vP07eA5ATtFa0wbYiOsHo1EE6S+dZA0wRHW16
        tID1YRKMgcGgdM5ueBpWwQkN98N74XEYCPUkHeGqhpU1Mlw9U8ka4cqbDkNB
        I0PEeXWltS/I0O+AH8LPwkvDYjEYKvWOBsQO8dn6kWXeRslqmKdXlKFjSBn2
        hkk9y/AW5y7exyvLY1nZzijZEgzXW+51bgMj4Ea4WGXabAiGa6TGu79uAAuI
        +6fV8WKT297K2HAN1HiN9rSzDtRocN+8WNSKIcuShgfjrJgHYC08B21gfugA
        j5hZc4qmBcUFyG/zfl/sptcXdwO3tGeyTEDnXAGGvdV/IjTDWPCA4DbiNqhx
        npjE/bYTjoDbj8XTimpfoZ9G7u3LlLKv/oiqPzLOw9CaxXDadcsK6skpnJ40
        xD58b5q4rQR0hMaG99wWZFu/s7q63+oId5LZsABuAc/rtdZ6OnwUVoHbYV1I
        R3oQsZ5o/CPQCqacjusN9rEc7gQPa3WrcBprZoaeKH8BbZD1kBKcZLS9Dt+C
        KWB0dcswrVc5t5AK/mV2K8yHmTAOrC1JaaznfP88XQmG9U7w/O9v3apnw7sn
        yY3ztMAaqtaEsWBajAKLotFgEbWo7i1e4z9meHW+/gcJp1Uhva1OQgAAAABJ
        RU5ErkJggg==
        """, options: .ignoreUnknownCharacters)!
}
