// Generated by Tools/generate_csharp_tables.py from the Swift engine's own
// tables, via `latex-squiggly --dump-tables`. Do not edit by hand: edit the
// Swift side and regenerate, or the two platforms drift apart.

namespace LaTeXSquiggly.Core.Engine;

public static class ScriptTables
{
    /// <summary>Characters with a Unicode superscript form: 40 of them.</summary>
    public static readonly IReadOnlyDictionary<char, char> Superscripts = new Dictionary<char, char>
    {
        { '(', '\u207D' },
        { ')', '\u207E' },
        { '+', '\u207A' },
        { '-', '\u207B' },
        { '0', '\u2070' },
        { '1', '\u00B9' },
        { '2', '\u00B2' },
        { '3', '\u00B3' },
        { '4', '\u2074' },
        { '5', '\u2075' },
        { '6', '\u2076' },
        { '7', '\u2077' },
        { '8', '\u2078' },
        { '9', '\u2079' },
        { '=', '\u207C' },
        { 'a', '\u1D43' },
        { 'b', '\u1D47' },
        { 'c', '\u1D9C' },
        { 'd', '\u1D48' },
        { 'e', '\u1D49' },
        { 'f', '\u1DA0' },
        { 'g', '\u1D4D' },
        { 'h', '\u02B0' },
        { 'i', '\u2071' },
        { 'j', '\u02B2' },
        { 'k', '\u1D4F' },
        { 'l', '\u02E1' },
        { 'm', '\u1D50' },
        { 'n', '\u207F' },
        { 'o', '\u1D52' },
        { 'p', '\u1D56' },
        { 'r', '\u02B3' },
        { 's', '\u02E2' },
        { 't', '\u1D57' },
        { 'u', '\u1D58' },
        { 'v', '\u1D5B' },
        { 'w', '\u02B7' },
        { 'x', '\u02E3' },
        { 'y', '\u02B8' },
        { 'z', '\u1DBB' },
    };

    /// <summary>Characters with a Unicode subscript form: 32 of them.
    /// Missing b c d f g q w y z, which must stay unsupported.</summary>
    public static readonly IReadOnlyDictionary<char, char> Subscripts = new Dictionary<char, char>
    {
        { '(', '\u208D' },
        { ')', '\u208E' },
        { '+', '\u208A' },
        { '-', '\u208B' },
        { '0', '\u2080' },
        { '1', '\u2081' },
        { '2', '\u2082' },
        { '3', '\u2083' },
        { '4', '\u2084' },
        { '5', '\u2085' },
        { '6', '\u2086' },
        { '7', '\u2087' },
        { '8', '\u2088' },
        { '9', '\u2089' },
        { '=', '\u208C' },
        { 'a', '\u2090' },
        { 'e', '\u2091' },
        { 'h', '\u2095' },
        { 'i', '\u1D62' },
        { 'j', '\u2C7C' },
        { 'k', '\u2096' },
        { 'l', '\u2097' },
        { 'm', '\u2098' },
        { 'n', '\u2099' },
        { 'o', '\u2092' },
        { 'p', '\u209A' },
        { 'r', '\u1D63' },
        { 's', '\u209B' },
        { 't', '\u209C' },
        { 'u', '\u1D64' },
        { 'v', '\u1D65' },
        { 'x', '\u2093' },
    };

    /// <summary>Radical signs by index. Only these three exist as single characters.</summary>
    public static readonly IReadOnlyDictionary<int, char> Radicals = new Dictionary<int, char>
    {
        { 2, '\u221A' },
        { 3, '\u221B' },
        { 4, '\u221C' },
    };

    /// <summary>Precomposed fractions, keyed "numerator/denominator".</summary>
    public static readonly IReadOnlyDictionary<string, string> VulgarFractions = new Dictionary<string, string>
    {
        { "0/3", "\u2189" },
        { "1/10", "\u2152" },
        { "1/2", "\u00BD" },
        { "1/3", "\u2153" },
        { "1/4", "\u00BC" },
        { "1/5", "\u2155" },
        { "1/6", "\u2159" },
        { "1/7", "\u2150" },
        { "1/8", "\u215B" },
        { "1/9", "\u2151" },
        { "2/3", "\u2154" },
        { "2/5", "\u2156" },
        { "3/4", "\u00BE" },
        { "3/5", "\u2157" },
        { "3/8", "\u215C" },
        { "4/5", "\u2158" },
        { "5/6", "\u215A" },
        { "5/8", "\u215D" },
        { "7/8", "\u215E" },
    };

    public const char FractionSlash = '\u2044';
}
