// Generated by Tools/generate_csharp_tables.py from the Swift engine's own
// tables, via `latex-squiggly --dump-tables`. Do not edit by hand: edit the
// Swift side and regenerate, or the two platforms drift apart.

namespace LaTeXSquiggly.Core.Engine;

/// <summary>
/// Named operators. LaTeX sets these upright, which in plain Unicode text is
/// simply the letters themselves, so these are genuine conversions.
/// </summary>
public static class TextOperators
{
    public static readonly IReadOnlyDictionary<string, string> Operators = new Dictionary<string, string>
    {
        { "Pr", "Pr" },
        { "arccos", "arccos" },
        { "arcsin", "arcsin" },
        { "arctan", "arctan" },
        { "arg", "arg" },
        { "bmod", "mod" },
        { "cos", "cos" },
        { "cosh", "cosh" },
        { "cot", "cot" },
        { "coth", "coth" },
        { "csc", "csc" },
        { "deg", "deg" },
        { "det", "det" },
        { "dim", "dim" },
        { "exp", "exp" },
        { "gcd", "gcd" },
        { "hom", "hom" },
        { "inf", "inf" },
        { "ker", "ker" },
        { "lg", "lg" },
        { "lim", "lim" },
        { "liminf", "liminf" },
        { "limsup", "limsup" },
        { "ln", "ln" },
        { "log", "log" },
        { "max", "max" },
        { "min", "min" },
        { "sec", "sec" },
        { "sin", "sin" },
        { "sinh", "sinh" },
        { "sup", "sup" },
        { "tan", "tan" },
        { "tanh", "tanh" },
    };
}
