// Generated by Tools/generate_csharp_tables.py from the Swift engine's own
// tables, via `latex-squiggly --dump-tables`. Do not edit by hand: edit the
// Swift side and regenerate, or the two platforms drift apart.

namespace LaTeXSquiggly.Core.Engine;

/// <summary>
/// Commands that are recognised but deliberately refused, each with the
/// explanation the user sees. Recognising them is the point: "Unknown command
/// \vec" suggests a typo, the real message tells the truth about the constraint.
/// </summary>
public static class UnsupportedCommands
{
    public static readonly IReadOnlyDictionary<string, string> Reasons = new Dictionary<string, string>
    {
        { "acute", "An accent cannot be drawn over other characters in plain text." },
        { "atop", "\\atop needs two-dimensional layout, which has no inline Unicode form." },
        { "bar", "An accent cannot be drawn over other characters in plain text." },
        { "boldsymbol", "Bold, script and fraktur alphabets are not supported yet." },
        { "breve", "An accent cannot be drawn over other characters in plain text." },
        { "cases", "The cases environment needs two-dimensional layout, which has no inline Unicode form." },
        { "choose", "\\choose needs two-dimensional layout, which has no inline Unicode form. Try \\binom{n}{k}, which falls back to C(n, k)." },
        { "cite", "\\cite belongs to a LaTeX document, not to inline text." },
        { "ddot", "An accent cannot be drawn over other characters in plain text." },
        { "displaystyle", "\\displaystyle only affects typeset size; there is nothing to insert." },
        { "dot", "An accent cannot be drawn over other characters in plain text." },
        { "emph", "Italic alphabets are not supported yet." },
        { "footnote", "\\footnote belongs to a LaTeX document, not to inline text." },
        { "grave", "An accent cannot be drawn over other characters in plain text." },
        { "hat", "An accent cannot be drawn over other characters in plain text." },
        { "hspace", "Spacing commands are typographic adjustments with no plain-text equivalent." },
        { "label", "\\label belongs to a LaTeX document, not to inline text." },
        { "limits", "\\limits only affects typeset placement; there is nothing to insert." },
        { "mathbf", "Bold, script and fraktur alphabets are not supported yet." },
        { "mathcal", "Bold, script and fraktur alphabets are not supported yet." },
        { "mathfrak", "Bold, script and fraktur alphabets are not supported yet." },
        { "mathit", "Italic alphabets are not supported yet." },
        { "mathring", "An accent cannot be drawn over other characters in plain text." },
        { "mathscr", "Bold, script and fraktur alphabets are not supported yet." },
        { "mathsf", "Sans-serif alphabets are not supported yet." },
        { "mathtt", "Monospace alphabets are not supported yet." },
        { "matrix", "A matrix needs two-dimensional layout, which has no inline Unicode form." },
        { "nolimits", "\\nolimits only affects typeset placement; there is nothing to insert." },
        { "over", "\\over needs two-dimensional layout, which has no inline Unicode form. Try \\frac{a}{b}, which falls back to a/b." },
        { "overbrace", "An overbrace cannot be drawn over other characters in plain text." },
        { "overleftarrow", "An arrow cannot be drawn over other characters in plain text." },
        { "overline", "An overline cannot be drawn over other characters in plain text." },
        { "overrightarrow", "An arrow cannot be drawn over other characters in plain text." },
        { "phantom", "\\phantom reserves typeset space; there is nothing to insert." },
        { "qquad", "Spacing commands are typographic adjustments with no plain-text equivalent." },
        { "quad", "Spacing commands are typographic adjustments with no plain-text equivalent." },
        { "ref", "\\ref belongs to a LaTeX document, not to inline text." },
        { "stackrel", "\\stackrel needs two-dimensional layout, which has no inline Unicode form." },
        { "substack", "\\substack needs two-dimensional layout, which has no inline Unicode form." },
        { "textbf", "Bold, script and fraktur alphabets are not supported yet." },
        { "textit", "Italic alphabets are not supported yet." },
        { "textstyle", "\\textstyle only affects typeset size; there is nothing to insert." },
        { "tilde", "An accent cannot be drawn over other characters in plain text." },
        { "underbrace", "An underbrace cannot be drawn over other characters in plain text." },
        { "underline", "An underline cannot be drawn over other characters in plain text." },
        { "vec", "An accent cannot be drawn over other characters in plain text." },
        { "vspace", "Spacing commands are typographic adjustments with no plain-text equivalent." },
        { "widehat", "An accent cannot be drawn over other characters in plain text." },
        { "widetilde", "An accent cannot be drawn over other characters in plain text." },
    };

    /// <summary><c>\{</c> and friends: an escaped literal is just that character.</summary>
    public static readonly IReadOnlyDictionary<char, char> EscapedLiterals = new Dictionary<char, char>
    {
        { '#', '#' },
        { '$', '$' },
        { '%', '%' },
        { '&', '&' },
        { '_', '_' },
        { '{', '{' },
        { '}', '}' },
    };

    /// <summary>Control symbols that are recognised but have no inline form.</summary>
    public static readonly IReadOnlyDictionary<char, string> SymbolReasons = new Dictionary<char, string>
    {
        { ' ', "Spacing commands are typographic adjustments with no plain-text equivalent." },
        { '!', "Spacing commands such as \\! are typographic adjustments with no plain-text equivalent." },
        { ',', "Spacing commands such as \\, are typographic adjustments with no plain-text equivalent." },
        { ':', "Spacing commands such as \\: are typographic adjustments with no plain-text equivalent." },
        { ';', "Spacing commands such as \\; are typographic adjustments with no plain-text equivalent." },
        { '\\', "A line break has no inline form \u2014 the replacement has to stay on one line." },
    };
}
