#!/usr/bin/env python3
"""
Generates chrome/engine/tables.js from the Swift engine's own tables.

The same reasoning as scripts/generate-csharp-tables.py: the extension has to hold
the same symbols, scripts and refusal messages as the Mac and Windows apps, and
a table transcribed by hand drifts the first time somebody adds a symbol to one
side. `latex-squiggly --dump-tables` prints the tables the Swift engine uses at
runtime, and this writes them out as a plain script the extension can load.

The output is JSON with every non-ASCII character escaped, so the file is pure
ASCII and reads the same whatever an editor guesses its encoding to be.

Run:  swift build && python3 scripts/generate-js-tables.py
"""

import json, os, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "chrome", "engine", "tables.js")

HEADER = """// Generated by scripts/generate-js-tables.py from the Swift engine's own
// tables, via `latex-squiggly --dump-tables`. Do not edit by hand: edit the
// Swift side and regenerate, or the platforms drift apart.
"""


def main():
    binary = os.path.join(ROOT, ".build", "debug", "latex-squiggly")
    if not os.path.exists(binary):
        sys.exit("build the Swift engine first: swift build")
    tables = json.loads(subprocess.check_output([binary, "--dump-tables"]))

    body = json.dumps(tables, ensure_ascii=True, indent=1, sort_keys=True)
    with open(OUT, "w", encoding="ascii") as handle:
        handle.write(HEADER)
        handle.write("\n(globalThis.LaTeXSquiggly ??= {}).tables = ")
        handle.write(body)
        handle.write(";\n")

    print(f"generated {len(tables['entries'])} symbols, "
          f"{len(tables['superscripts'])} superscripts, "
          f"{len(tables['subscripts'])} subscripts, "
          f"{len(tables['vulgarFractions'])} fractions, "
          f"{len(tables['operators'])} operators, "
          f"{len(tables['unsupportedReasons'])} refusals")


if __name__ == "__main__":
    main()
