#!/usr/bin/env python3
"""
Generates windows/LaTeXSquiggly.Core/Engine/*.g.cs from the Swift engine's own
tables.

Why a generator, again: the Windows port has to hold the same 202 symbols, the
same 40 superscripts and the same 49 refusal messages as the Mac app, and a
table transcribed by hand drifts the first time somebody adds a symbol to one
side. So nothing here is transcribed. `latex-squiggly --dump-tables` prints the
tables the Swift engine actually uses at runtime, and this turns that JSON into
C#. Re-run it whenever the Swift tables change.

Run:  swift build && python3 Tools/generate_csharp_tables.py
"""

import json, os, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "windows", "LaTeXSquiggly.Core", "Engine")

HEADER = """// Generated by Tools/generate_csharp_tables.py from the Swift engine's own
// tables, via `latex-squiggly --dump-tables`. Do not edit by hand: edit the
// Swift side and regenerate, or the two platforms drift apart.

namespace LaTeXSquiggly.Core.Engine;
"""


def cs_string(text):
    out = ['"']
    for ch in text:
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append("\\n")
        elif ord(ch) < 0x20:
            out.append("\\u%04X" % ord(ch))
        elif ord(ch) > 0x7E:
            # Escaped rather than literal so the file is pure ASCII and cannot
            # be mangled by an editor guessing at its encoding.
            for unit in ch.encode("utf-16-le"):
                pass
            encoded = ch.encode("utf-16-be")
            for i in range(0, len(encoded), 2):
                out.append("\\u%02X%02X" % (encoded[i], encoded[i + 1]))
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def cs_char(ch):
    assert len(ch) == 1, ch
    if ord(ch) > 0x7E or ord(ch) < 0x20:
        return "'\\u%04X'" % ord(ch)
    if ch == "'":
        return "'\\''"
    if ch == "\\":
        return "'\\\\'"
    return "'%s'" % ch


def dict_entries(pairs, key_fn, value_fn, indent=" " * 8):
    return "\n".join(
        "%s{ %s, %s }," % (indent, key_fn(k), value_fn(v)) for k, v in pairs
    )


def main():
    binary = os.path.join(ROOT, ".build", "debug", "latex-squiggly")
    if not os.path.exists(binary):
        sys.exit("build the Swift engine first: swift build")
    tables = json.loads(subprocess.check_output([binary, "--dump-tables"]))

    os.makedirs(OUT, exist_ok=True)

    # --- Symbols -----------------------------------------------------------
    entries = tables["entries"]
    rows = "\n".join(
        "        new(%s, %s, %s, %s),"
        % (cs_string(e["command"]), cs_string(e["glyph"]),
           cs_string(e["unicodeName"]), cs_string(e["category"]))
        for e in entries
    )
    write("SymbolTable.g.cs", f"""{HEADER}
/// <summary>One row of the coverage table, with enough context to be searchable.</summary>
public sealed record SymbolEntry(string Command, string Glyph, string UnicodeName, string Category);

public static class SymbolTable
{{
    /// <summary>{len(entries)} symbols, in table order.</summary>
    public static readonly SymbolEntry[] Entries =
    {{
{rows}
    }};

    /// <summary>LaTeX command name, without the backslash, to its Unicode form.</summary>
    public static readonly IReadOnlyDictionary<string, string> Symbols =
        Entries.ToDictionary(e => e.Command, e => e.Glyph);
}}
""")

    # --- Scripts and fractions --------------------------------------------
    sup = sorted(tables["superscripts"].items())
    sub = sorted(tables["subscripts"].items())
    radicals = sorted(tables["radicals"].items(), key=lambda kv: int(kv[0]))
    vulgar = sorted(tables["vulgarFractions"].items())
    write("ScriptTables.g.cs", f"""{HEADER}
public static class ScriptTables
{{
    /// <summary>Characters with a Unicode superscript form: {len(sup)} of them.</summary>
    public static readonly IReadOnlyDictionary<char, char> Superscripts = new Dictionary<char, char>
    {{
{dict_entries(sup, cs_char, cs_char)}
    }};

    /// <summary>Characters with a Unicode subscript form: {len(sub)} of them.
    /// Missing b c d f g q w y z, which must stay unsupported.</summary>
    public static readonly IReadOnlyDictionary<char, char> Subscripts = new Dictionary<char, char>
    {{
{dict_entries(sub, cs_char, cs_char)}
    }};

    /// <summary>Radical signs by index. Only these three exist as single characters.</summary>
    public static readonly IReadOnlyDictionary<int, char> Radicals = new Dictionary<int, char>
    {{
{dict_entries(radicals, lambda k: k, cs_char)}
    }};

    /// <summary>Precomposed fractions, keyed "numerator/denominator".</summary>
    public static readonly IReadOnlyDictionary<string, string> VulgarFractions = new Dictionary<string, string>
    {{
{dict_entries(vulgar, cs_string, cs_string)}
    }};

    public const char FractionSlash = {cs_char(tables["fractionSlash"])};
}}
""")

    # --- Named operators ---------------------------------------------------
    ops = sorted(tables["operators"].items())
    write("TextOperators.g.cs", f"""{HEADER}
/// <summary>
/// Named operators. LaTeX sets these upright, which in plain Unicode text is
/// simply the letters themselves, so these are genuine conversions.
/// </summary>
public static class TextOperators
{{
    public static readonly IReadOnlyDictionary<string, string> Operators = new Dictionary<string, string>
    {{
{dict_entries(ops, cs_string, cs_string)}
    }};
}}
""")

    # --- Refusals ----------------------------------------------------------
    reasons = sorted(tables["unsupportedReasons"].items())
    literals = sorted(tables["escapedLiterals"].items())
    symbol_reasons = sorted(tables["symbolReasons"].items())
    write("UnsupportedCommands.g.cs", f"""{HEADER}
/// <summary>
/// Commands that are recognised but deliberately refused, each with the
/// explanation the user sees. Recognising them is the point: "Unknown command
/// \\vec" suggests a typo, the real message tells the truth about the constraint.
/// </summary>
public static class UnsupportedCommands
{{
    public static readonly IReadOnlyDictionary<string, string> Reasons = new Dictionary<string, string>
    {{
{dict_entries(reasons, cs_string, cs_string)}
    }};

    /// <summary><c>\\{{</c> and friends: an escaped literal is just that character.</summary>
    public static readonly IReadOnlyDictionary<char, char> EscapedLiterals = new Dictionary<char, char>
    {{
{dict_entries(literals, cs_char, cs_char)}
    }};

    /// <summary>Control symbols that are recognised but have no inline form.</summary>
    public static readonly IReadOnlyDictionary<char, string> SymbolReasons = new Dictionary<char, string>
    {{
{dict_entries(symbol_reasons, cs_char, cs_string)}
    }};
}}
""")

    print(f"generated {len(entries)} symbols, {len(sup)} superscripts, "
          f"{len(sub)} subscripts, {len(vulgar)} fractions, {len(ops)} operators, "
          f"{len(reasons)} refusals")


def write(name, text):
    with open(os.path.join(OUT, name), "w", encoding="ascii") as handle:
        handle.write(text)


if __name__ == "__main__":
    main()
