// Generated by scripts/generate-js-tables.py from the Swift engine's own
// tables, via `latex-squiggly --dump-tables`. Do not edit by hand: edit the
// Swift side and regenerate, or the platforms drift apart.

(globalThis.LaTeXSquiggly ??= {}).tables = {
 "entries": [
  {
   "category": "Greek, lower case",
   "command": "alpha",
   "glyph": "\u03b1",
   "unicodeName": "GREEK SMALL LETTER ALPHA"
  },
  {
   "category": "Greek, lower case",
   "command": "beta",
   "glyph": "\u03b2",
   "unicodeName": "GREEK SMALL LETTER BETA"
  },
  {
   "category": "Greek, lower case",
   "command": "gamma",
   "glyph": "\u03b3",
   "unicodeName": "GREEK SMALL LETTER GAMMA"
  },
  {
   "category": "Greek, lower case",
   "command": "delta",
   "glyph": "\u03b4",
   "unicodeName": "GREEK SMALL LETTER DELTA"
  },
  {
   "category": "Greek, lower case",
   "command": "epsilon",
   "glyph": "\u03f5",
   "unicodeName": "GREEK LUNATE EPSILON SYMBOL"
  },
  {
   "category": "Greek, lower case",
   "command": "varepsilon",
   "glyph": "\u03b5",
   "unicodeName": "GREEK SMALL LETTER EPSILON"
  },
  {
   "category": "Greek, lower case",
   "command": "zeta",
   "glyph": "\u03b6",
   "unicodeName": "GREEK SMALL LETTER ZETA"
  },
  {
   "category": "Greek, lower case",
   "command": "eta",
   "glyph": "\u03b7",
   "unicodeName": "GREEK SMALL LETTER ETA"
  },
  {
   "category": "Greek, lower case",
   "command": "theta",
   "glyph": "\u03b8",
   "unicodeName": "GREEK SMALL LETTER THETA"
  },
  {
   "category": "Greek, lower case",
   "command": "vartheta",
   "glyph": "\u03d1",
   "unicodeName": "GREEK THETA SYMBOL"
  },
  {
   "category": "Greek, lower case",
   "command": "iota",
   "glyph": "\u03b9",
   "unicodeName": "GREEK SMALL LETTER IOTA"
  },
  {
   "category": "Greek, lower case",
   "command": "kappa",
   "glyph": "\u03ba",
   "unicodeName": "GREEK SMALL LETTER KAPPA"
  },
  {
   "category": "Greek, lower case",
   "command": "lambda",
   "glyph": "\u03bb",
   "unicodeName": "GREEK SMALL LETTER LAMDA"
  },
  {
   "category": "Greek, lower case",
   "command": "mu",
   "glyph": "\u03bc",
   "unicodeName": "GREEK SMALL LETTER MU"
  },
  {
   "category": "Greek, lower case",
   "command": "nu",
   "glyph": "\u03bd",
   "unicodeName": "GREEK SMALL LETTER NU"
  },
  {
   "category": "Greek, lower case",
   "command": "xi",
   "glyph": "\u03be",
   "unicodeName": "GREEK SMALL LETTER XI"
  },
  {
   "category": "Greek, lower case",
   "command": "omicron",
   "glyph": "\u03bf",
   "unicodeName": "GREEK SMALL LETTER OMICRON"
  },
  {
   "category": "Greek, lower case",
   "command": "pi",
   "glyph": "\u03c0",
   "unicodeName": "GREEK SMALL LETTER PI"
  },
  {
   "category": "Greek, lower case",
   "command": "varpi",
   "glyph": "\u03d6",
   "unicodeName": "GREEK PI SYMBOL"
  },
  {
   "category": "Greek, lower case",
   "command": "rho",
   "glyph": "\u03c1",
   "unicodeName": "GREEK SMALL LETTER RHO"
  },
  {
   "category": "Greek, lower case",
   "command": "varrho",
   "glyph": "\u03f1",
   "unicodeName": "GREEK RHO SYMBOL"
  },
  {
   "category": "Greek, lower case",
   "command": "sigma",
   "glyph": "\u03c3",
   "unicodeName": "GREEK SMALL LETTER SIGMA"
  },
  {
   "category": "Greek, lower case",
   "command": "varsigma",
   "glyph": "\u03c2",
   "unicodeName": "GREEK SMALL LETTER FINAL SIGMA"
  },
  {
   "category": "Greek, lower case",
   "command": "tau",
   "glyph": "\u03c4",
   "unicodeName": "GREEK SMALL LETTER TAU"
  },
  {
   "category": "Greek, lower case",
   "command": "upsilon",
   "glyph": "\u03c5",
   "unicodeName": "GREEK SMALL LETTER UPSILON"
  },
  {
   "category": "Greek, lower case",
   "command": "phi",
   "glyph": "\u03d5",
   "unicodeName": "GREEK PHI SYMBOL"
  },
  {
   "category": "Greek, lower case",
   "command": "varphi",
   "glyph": "\u03c6",
   "unicodeName": "GREEK SMALL LETTER PHI"
  },
  {
   "category": "Greek, lower case",
   "command": "chi",
   "glyph": "\u03c7",
   "unicodeName": "GREEK SMALL LETTER CHI"
  },
  {
   "category": "Greek, lower case",
   "command": "psi",
   "glyph": "\u03c8",
   "unicodeName": "GREEK SMALL LETTER PSI"
  },
  {
   "category": "Greek, lower case",
   "command": "omega",
   "glyph": "\u03c9",
   "unicodeName": "GREEK SMALL LETTER OMEGA"
  },
  {
   "category": "Greek, upper case",
   "command": "Gamma",
   "glyph": "\u0393",
   "unicodeName": "GREEK CAPITAL LETTER GAMMA"
  },
  {
   "category": "Greek, upper case",
   "command": "Delta",
   "glyph": "\u0394",
   "unicodeName": "GREEK CAPITAL LETTER DELTA"
  },
  {
   "category": "Greek, upper case",
   "command": "Theta",
   "glyph": "\u0398",
   "unicodeName": "GREEK CAPITAL LETTER THETA"
  },
  {
   "category": "Greek, upper case",
   "command": "Lambda",
   "glyph": "\u039b",
   "unicodeName": "GREEK CAPITAL LETTER LAMDA"
  },
  {
   "category": "Greek, upper case",
   "command": "Xi",
   "glyph": "\u039e",
   "unicodeName": "GREEK CAPITAL LETTER XI"
  },
  {
   "category": "Greek, upper case",
   "command": "Pi",
   "glyph": "\u03a0",
   "unicodeName": "GREEK CAPITAL LETTER PI"
  },
  {
   "category": "Greek, upper case",
   "command": "Sigma",
   "glyph": "\u03a3",
   "unicodeName": "GREEK CAPITAL LETTER SIGMA"
  },
  {
   "category": "Greek, upper case",
   "command": "Upsilon",
   "glyph": "\u03a5",
   "unicodeName": "GREEK CAPITAL LETTER UPSILON"
  },
  {
   "category": "Greek, upper case",
   "command": "Phi",
   "glyph": "\u03a6",
   "unicodeName": "GREEK CAPITAL LETTER PHI"
  },
  {
   "category": "Greek, upper case",
   "command": "Psi",
   "glyph": "\u03a8",
   "unicodeName": "GREEK CAPITAL LETTER PSI"
  },
  {
   "category": "Greek, upper case",
   "command": "Omega",
   "glyph": "\u03a9",
   "unicodeName": "GREEK CAPITAL LETTER OMEGA"
  },
  {
   "category": "Operators",
   "command": "int",
   "glyph": "\u222b",
   "unicodeName": "INTEGRAL"
  },
  {
   "category": "Operators",
   "command": "iint",
   "glyph": "\u222c",
   "unicodeName": "DOUBLE INTEGRAL"
  },
  {
   "category": "Operators",
   "command": "iiint",
   "glyph": "\u222d",
   "unicodeName": "TRIPLE INTEGRAL"
  },
  {
   "category": "Operators",
   "command": "oint",
   "glyph": "\u222e",
   "unicodeName": "CONTOUR INTEGRAL"
  },
  {
   "category": "Operators",
   "command": "sum",
   "glyph": "\u2211",
   "unicodeName": "N-ARY SUMMATION"
  },
  {
   "category": "Operators",
   "command": "prod",
   "glyph": "\u220f",
   "unicodeName": "N-ARY PRODUCT"
  },
  {
   "category": "Operators",
   "command": "coprod",
   "glyph": "\u2210",
   "unicodeName": "N-ARY COPRODUCT"
  },
  {
   "category": "Operators",
   "command": "bigcup",
   "glyph": "\u22c3",
   "unicodeName": "N-ARY UNION"
  },
  {
   "category": "Operators",
   "command": "bigcap",
   "glyph": "\u22c2",
   "unicodeName": "N-ARY INTERSECTION"
  },
  {
   "category": "Operators",
   "command": "bigoplus",
   "glyph": "\u2a01",
   "unicodeName": "N-ARY CIRCLED PLUS OPERATOR"
  },
  {
   "category": "Operators",
   "command": "bigotimes",
   "glyph": "\u2a02",
   "unicodeName": "N-ARY CIRCLED TIMES OPERATOR"
  },
  {
   "category": "Operators",
   "command": "bigvee",
   "glyph": "\u22c1",
   "unicodeName": "N-ARY LOGICAL OR"
  },
  {
   "category": "Operators",
   "command": "bigwedge",
   "glyph": "\u22c0",
   "unicodeName": "N-ARY LOGICAL AND"
  },
  {
   "category": "Operators",
   "command": "pm",
   "glyph": "\u00b1",
   "unicodeName": "PLUS-MINUS SIGN"
  },
  {
   "category": "Operators",
   "command": "mp",
   "glyph": "\u2213",
   "unicodeName": "MINUS-OR-PLUS SIGN"
  },
  {
   "category": "Operators",
   "command": "times",
   "glyph": "\u00d7",
   "unicodeName": "MULTIPLICATION SIGN"
  },
  {
   "category": "Operators",
   "command": "div",
   "glyph": "\u00f7",
   "unicodeName": "DIVISION SIGN"
  },
  {
   "category": "Operators",
   "command": "cdot",
   "glyph": "\u22c5",
   "unicodeName": "DOT OPERATOR"
  },
  {
   "category": "Operators",
   "command": "circ",
   "glyph": "\u2218",
   "unicodeName": "RING OPERATOR"
  },
  {
   "category": "Operators",
   "command": "bullet",
   "glyph": "\u2219",
   "unicodeName": "BULLET OPERATOR"
  },
  {
   "category": "Operators",
   "command": "ast",
   "glyph": "\u2217",
   "unicodeName": "ASTERISK OPERATOR"
  },
  {
   "category": "Operators",
   "command": "star",
   "glyph": "\u22c6",
   "unicodeName": "STAR OPERATOR"
  },
  {
   "category": "Operators",
   "command": "oplus",
   "glyph": "\u2295",
   "unicodeName": "CIRCLED PLUS"
  },
  {
   "category": "Operators",
   "command": "ominus",
   "glyph": "\u2296",
   "unicodeName": "CIRCLED MINUS"
  },
  {
   "category": "Operators",
   "command": "otimes",
   "glyph": "\u2297",
   "unicodeName": "CIRCLED TIMES"
  },
  {
   "category": "Operators",
   "command": "oslash",
   "glyph": "\u2298",
   "unicodeName": "CIRCLED DIVISION SLASH"
  },
  {
   "category": "Operators",
   "command": "odot",
   "glyph": "\u2299",
   "unicodeName": "CIRCLED DOT OPERATOR"
  },
  {
   "category": "Operators",
   "command": "infty",
   "glyph": "\u221e",
   "unicodeName": "INFINITY"
  },
  {
   "category": "Operators",
   "command": "partial",
   "glyph": "\u2202",
   "unicodeName": "PARTIAL DIFFERENTIAL"
  },
  {
   "category": "Operators",
   "command": "nabla",
   "glyph": "\u2207",
   "unicodeName": "NABLA"
  },
  {
   "category": "Operators",
   "command": "surd",
   "glyph": "\u221a",
   "unicodeName": "SQUARE ROOT"
  },
  {
   "category": "Operators",
   "command": "prime",
   "glyph": "\u2032",
   "unicodeName": "PRIME"
  },
  {
   "category": "Operators",
   "command": "degree",
   "glyph": "\u00b0",
   "unicodeName": "DEGREE SIGN"
  },
  {
   "category": "Relations",
   "command": "leq",
   "glyph": "\u2264",
   "unicodeName": "LESS-THAN OR EQUAL TO"
  },
  {
   "category": "Relations",
   "command": "le",
   "glyph": "\u2264",
   "unicodeName": "LESS-THAN OR EQUAL TO"
  },
  {
   "category": "Relations",
   "command": "geq",
   "glyph": "\u2265",
   "unicodeName": "GREATER-THAN OR EQUAL TO"
  },
  {
   "category": "Relations",
   "command": "ge",
   "glyph": "\u2265",
   "unicodeName": "GREATER-THAN OR EQUAL TO"
  },
  {
   "category": "Relations",
   "command": "neq",
   "glyph": "\u2260",
   "unicodeName": "NOT EQUAL TO"
  },
  {
   "category": "Relations",
   "command": "ne",
   "glyph": "\u2260",
   "unicodeName": "NOT EQUAL TO"
  },
  {
   "category": "Relations",
   "command": "approx",
   "glyph": "\u2248",
   "unicodeName": "ALMOST EQUAL TO"
  },
  {
   "category": "Relations",
   "command": "equiv",
   "glyph": "\u2261",
   "unicodeName": "IDENTICAL TO"
  },
  {
   "category": "Relations",
   "command": "sim",
   "glyph": "\u223c",
   "unicodeName": "TILDE OPERATOR"
  },
  {
   "category": "Relations",
   "command": "simeq",
   "glyph": "\u2243",
   "unicodeName": "ASYMPTOTICALLY EQUAL TO"
  },
  {
   "category": "Relations",
   "command": "cong",
   "glyph": "\u2245",
   "unicodeName": "APPROXIMATELY EQUAL TO"
  },
  {
   "category": "Relations",
   "command": "propto",
   "glyph": "\u221d",
   "unicodeName": "PROPORTIONAL TO"
  },
  {
   "category": "Relations",
   "command": "ll",
   "glyph": "\u226a",
   "unicodeName": "MUCH LESS-THAN"
  },
  {
   "category": "Relations",
   "command": "gg",
   "glyph": "\u226b",
   "unicodeName": "MUCH GREATER-THAN"
  },
  {
   "category": "Relations",
   "command": "prec",
   "glyph": "\u227a",
   "unicodeName": "PRECEDES"
  },
  {
   "category": "Relations",
   "command": "succ",
   "glyph": "\u227b",
   "unicodeName": "SUCCEEDS"
  },
  {
   "category": "Relations",
   "command": "preceq",
   "glyph": "\u227c",
   "unicodeName": "PRECEDES OR EQUAL TO"
  },
  {
   "category": "Relations",
   "command": "succeq",
   "glyph": "\u227d",
   "unicodeName": "SUCCEEDS OR EQUAL TO"
  },
  {
   "category": "Relations",
   "command": "perp",
   "glyph": "\u22a5",
   "unicodeName": "UP TACK"
  },
  {
   "category": "Relations",
   "command": "bot",
   "glyph": "\u22a5",
   "unicodeName": "UP TACK"
  },
  {
   "category": "Relations",
   "command": "top",
   "glyph": "\u22a4",
   "unicodeName": "DOWN TACK"
  },
  {
   "category": "Relations",
   "command": "parallel",
   "glyph": "\u2225",
   "unicodeName": "PARALLEL TO"
  },
  {
   "category": "Relations",
   "command": "nparallel",
   "glyph": "\u2226",
   "unicodeName": "NOT PARALLEL TO"
  },
  {
   "category": "Relations",
   "command": "mid",
   "glyph": "\u2223",
   "unicodeName": "DIVIDES"
  },
  {
   "category": "Relations",
   "command": "nmid",
   "glyph": "\u2224",
   "unicodeName": "DOES NOT DIVIDE"
  },
  {
   "category": "Relations",
   "command": "nless",
   "glyph": "\u226e",
   "unicodeName": "NOT LESS-THAN"
  },
  {
   "category": "Relations",
   "command": "ngtr",
   "glyph": "\u226f",
   "unicodeName": "NOT GREATER-THAN"
  },
  {
   "category": "Relations",
   "command": "nleq",
   "glyph": "\u2270",
   "unicodeName": "NEITHER LESS-THAN NOR EQUAL TO"
  },
  {
   "category": "Relations",
   "command": "ngeq",
   "glyph": "\u2271",
   "unicodeName": "NEITHER GREATER-THAN NOR EQUAL TO"
  },
  {
   "category": "Relations",
   "command": "coloneqq",
   "glyph": "\u2254",
   "unicodeName": "COLON EQUALS"
  },
  {
   "category": "Set notation",
   "command": "in",
   "glyph": "\u2208",
   "unicodeName": "ELEMENT OF"
  },
  {
   "category": "Set notation",
   "command": "notin",
   "glyph": "\u2209",
   "unicodeName": "NOT AN ELEMENT OF"
  },
  {
   "category": "Set notation",
   "command": "ni",
   "glyph": "\u220b",
   "unicodeName": "CONTAINS AS MEMBER"
  },
  {
   "category": "Set notation",
   "command": "subset",
   "glyph": "\u2282",
   "unicodeName": "SUBSET OF"
  },
  {
   "category": "Set notation",
   "command": "supset",
   "glyph": "\u2283",
   "unicodeName": "SUPERSET OF"
  },
  {
   "category": "Set notation",
   "command": "subseteq",
   "glyph": "\u2286",
   "unicodeName": "SUBSET OF OR EQUAL TO"
  },
  {
   "category": "Set notation",
   "command": "supseteq",
   "glyph": "\u2287",
   "unicodeName": "SUPERSET OF OR EQUAL TO"
  },
  {
   "category": "Set notation",
   "command": "nsubseteq",
   "glyph": "\u2288",
   "unicodeName": "NEITHER A SUBSET OF NOR EQUAL TO"
  },
  {
   "category": "Set notation",
   "command": "nsupseteq",
   "glyph": "\u2289",
   "unicodeName": "NEITHER A SUPERSET OF NOR EQUAL TO"
  },
  {
   "category": "Set notation",
   "command": "subsetneq",
   "glyph": "\u228a",
   "unicodeName": "SUBSET OF WITH NOT EQUAL TO"
  },
  {
   "category": "Set notation",
   "command": "supsetneq",
   "glyph": "\u228b",
   "unicodeName": "SUPERSET OF WITH NOT EQUAL TO"
  },
  {
   "category": "Set notation",
   "command": "cup",
   "glyph": "\u222a",
   "unicodeName": "UNION"
  },
  {
   "category": "Set notation",
   "command": "cap",
   "glyph": "\u2229",
   "unicodeName": "INTERSECTION"
  },
  {
   "category": "Set notation",
   "command": "uplus",
   "glyph": "\u228e",
   "unicodeName": "MULTISET UNION"
  },
  {
   "category": "Set notation",
   "command": "sqcup",
   "glyph": "\u2294",
   "unicodeName": "SQUARE CUP"
  },
  {
   "category": "Set notation",
   "command": "sqcap",
   "glyph": "\u2293",
   "unicodeName": "SQUARE CAP"
  },
  {
   "category": "Set notation",
   "command": "setminus",
   "glyph": "\u2216",
   "unicodeName": "SET MINUS"
  },
  {
   "category": "Set notation",
   "command": "emptyset",
   "glyph": "\u2205",
   "unicodeName": "EMPTY SET"
  },
  {
   "category": "Set notation",
   "command": "varnothing",
   "glyph": "\u2205",
   "unicodeName": "EMPTY SET"
  },
  {
   "category": "Set notation",
   "command": "forall",
   "glyph": "\u2200",
   "unicodeName": "FOR ALL"
  },
  {
   "category": "Set notation",
   "command": "exists",
   "glyph": "\u2203",
   "unicodeName": "THERE EXISTS"
  },
  {
   "category": "Set notation",
   "command": "nexists",
   "glyph": "\u2204",
   "unicodeName": "THERE DOES NOT EXIST"
  },
  {
   "category": "Logic",
   "command": "land",
   "glyph": "\u2227",
   "unicodeName": "LOGICAL AND"
  },
  {
   "category": "Logic",
   "command": "wedge",
   "glyph": "\u2227",
   "unicodeName": "LOGICAL AND"
  },
  {
   "category": "Logic",
   "command": "lor",
   "glyph": "\u2228",
   "unicodeName": "LOGICAL OR"
  },
  {
   "category": "Logic",
   "command": "vee",
   "glyph": "\u2228",
   "unicodeName": "LOGICAL OR"
  },
  {
   "category": "Logic",
   "command": "neg",
   "glyph": "\u00ac",
   "unicodeName": "NOT SIGN"
  },
  {
   "category": "Logic",
   "command": "lnot",
   "glyph": "\u00ac",
   "unicodeName": "NOT SIGN"
  },
  {
   "category": "Logic",
   "command": "models",
   "glyph": "\u22a8",
   "unicodeName": "TRUE"
  },
  {
   "category": "Logic",
   "command": "vdash",
   "glyph": "\u22a2",
   "unicodeName": "RIGHT TACK"
  },
  {
   "category": "Logic",
   "command": "dashv",
   "glyph": "\u22a3",
   "unicodeName": "LEFT TACK"
  },
  {
   "category": "Logic",
   "command": "therefore",
   "glyph": "\u2234",
   "unicodeName": "THEREFORE"
  },
  {
   "category": "Logic",
   "command": "because",
   "glyph": "\u2235",
   "unicodeName": "BECAUSE"
  },
  {
   "category": "Arrows",
   "command": "leftarrow",
   "glyph": "\u2190",
   "unicodeName": "LEFTWARDS ARROW"
  },
  {
   "category": "Arrows",
   "command": "gets",
   "glyph": "\u2190",
   "unicodeName": "LEFTWARDS ARROW"
  },
  {
   "category": "Arrows",
   "command": "rightarrow",
   "glyph": "\u2192",
   "unicodeName": "RIGHTWARDS ARROW"
  },
  {
   "category": "Arrows",
   "command": "to",
   "glyph": "\u2192",
   "unicodeName": "RIGHTWARDS ARROW"
  },
  {
   "category": "Arrows",
   "command": "uparrow",
   "glyph": "\u2191",
   "unicodeName": "UPWARDS ARROW"
  },
  {
   "category": "Arrows",
   "command": "downarrow",
   "glyph": "\u2193",
   "unicodeName": "DOWNWARDS ARROW"
  },
  {
   "category": "Arrows",
   "command": "leftrightarrow",
   "glyph": "\u2194",
   "unicodeName": "LEFT RIGHT ARROW"
  },
  {
   "category": "Arrows",
   "command": "updownarrow",
   "glyph": "\u2195",
   "unicodeName": "UP DOWN ARROW"
  },
  {
   "category": "Arrows",
   "command": "nearrow",
   "glyph": "\u2197",
   "unicodeName": "NORTH EAST ARROW"
  },
  {
   "category": "Arrows",
   "command": "searrow",
   "glyph": "\u2198",
   "unicodeName": "SOUTH EAST ARROW"
  },
  {
   "category": "Arrows",
   "command": "swarrow",
   "glyph": "\u2199",
   "unicodeName": "SOUTH WEST ARROW"
  },
  {
   "category": "Arrows",
   "command": "nwarrow",
   "glyph": "\u2196",
   "unicodeName": "NORTH WEST ARROW"
  },
  {
   "category": "Arrows",
   "command": "mapsto",
   "glyph": "\u21a6",
   "unicodeName": "RIGHTWARDS ARROW FROM BAR"
  },
  {
   "category": "Arrows",
   "command": "hookleftarrow",
   "glyph": "\u21a9",
   "unicodeName": "LEFTWARDS ARROW WITH HOOK"
  },
  {
   "category": "Arrows",
   "command": "hookrightarrow",
   "glyph": "\u21aa",
   "unicodeName": "RIGHTWARDS ARROW WITH HOOK"
  },
  {
   "category": "Arrows",
   "command": "rightleftharpoons",
   "glyph": "\u21cc",
   "unicodeName": "RIGHTWARDS HARPOON OVER LEFTWARDS HARPOON"
  },
  {
   "category": "Arrows",
   "command": "Leftarrow",
   "glyph": "\u21d0",
   "unicodeName": "LEFTWARDS DOUBLE ARROW"
  },
  {
   "category": "Arrows",
   "command": "Rightarrow",
   "glyph": "\u21d2",
   "unicodeName": "RIGHTWARDS DOUBLE ARROW"
  },
  {
   "category": "Arrows",
   "command": "Uparrow",
   "glyph": "\u21d1",
   "unicodeName": "UPWARDS DOUBLE ARROW"
  },
  {
   "category": "Arrows",
   "command": "Downarrow",
   "glyph": "\u21d3",
   "unicodeName": "DOWNWARDS DOUBLE ARROW"
  },
  {
   "category": "Arrows",
   "command": "Leftrightarrow",
   "glyph": "\u21d4",
   "unicodeName": "LEFT RIGHT DOUBLE ARROW"
  },
  {
   "category": "Arrows",
   "command": "Updownarrow",
   "glyph": "\u21d5",
   "unicodeName": "UP DOWN DOUBLE ARROW"
  },
  {
   "category": "Arrows",
   "command": "longleftarrow",
   "glyph": "\u27f5",
   "unicodeName": "LONG LEFTWARDS ARROW"
  },
  {
   "category": "Arrows",
   "command": "longrightarrow",
   "glyph": "\u27f6",
   "unicodeName": "LONG RIGHTWARDS ARROW"
  },
  {
   "category": "Arrows",
   "command": "longleftrightarrow",
   "glyph": "\u27f7",
   "unicodeName": "LONG LEFT RIGHT ARROW"
  },
  {
   "category": "Arrows",
   "command": "Longleftarrow",
   "glyph": "\u27f8",
   "unicodeName": "LONG LEFTWARDS DOUBLE ARROW"
  },
  {
   "category": "Arrows",
   "command": "Longrightarrow",
   "glyph": "\u27f9",
   "unicodeName": "LONG RIGHTWARDS DOUBLE ARROW"
  },
  {
   "category": "Arrows",
   "command": "Longleftrightarrow",
   "glyph": "\u27fa",
   "unicodeName": "LONG LEFT RIGHT DOUBLE ARROW"
  },
  {
   "category": "Arrows",
   "command": "implies",
   "glyph": "\u27f9",
   "unicodeName": "LONG RIGHTWARDS DOUBLE ARROW"
  },
  {
   "category": "Arrows",
   "command": "impliedby",
   "glyph": "\u27f8",
   "unicodeName": "LONG LEFTWARDS DOUBLE ARROW"
  },
  {
   "category": "Arrows",
   "command": "iff",
   "glyph": "\u27fa",
   "unicodeName": "LONG LEFT RIGHT DOUBLE ARROW"
  },
  {
   "category": "Blackboard bold",
   "command": "R",
   "glyph": "\u211d",
   "unicodeName": "DOUBLE-STRUCK CAPITAL R"
  },
  {
   "category": "Blackboard bold",
   "command": "Q",
   "glyph": "\u211a",
   "unicodeName": "DOUBLE-STRUCK CAPITAL Q"
  },
  {
   "category": "Blackboard bold",
   "command": "Z",
   "glyph": "\u2124",
   "unicodeName": "DOUBLE-STRUCK CAPITAL Z"
  },
  {
   "category": "Blackboard bold",
   "command": "N",
   "glyph": "\u2115",
   "unicodeName": "DOUBLE-STRUCK CAPITAL N"
  },
  {
   "category": "Blackboard bold",
   "command": "C",
   "glyph": "\u2102",
   "unicodeName": "DOUBLE-STRUCK CAPITAL C"
  },
  {
   "category": "Blackboard bold",
   "command": "H",
   "glyph": "\u210d",
   "unicodeName": "DOUBLE-STRUCK CAPITAL H"
  },
  {
   "category": "Blackboard bold",
   "command": "E",
   "glyph": "\ud835\udd3c",
   "unicodeName": "MATHEMATICAL DOUBLE-STRUCK CAPITAL E"
  },
  {
   "category": "Blackboard bold",
   "command": "F",
   "glyph": "\ud835\udd3d",
   "unicodeName": "MATHEMATICAL DOUBLE-STRUCK CAPITAL F"
  },
  {
   "category": "Blackboard bold",
   "command": "P",
   "glyph": "\u2119",
   "unicodeName": "DOUBLE-STRUCK CAPITAL P"
  },
  {
   "category": "Delimiters",
   "command": "langle",
   "glyph": "\u27e8",
   "unicodeName": "MATHEMATICAL LEFT ANGLE BRACKET"
  },
  {
   "category": "Delimiters",
   "command": "rangle",
   "glyph": "\u27e9",
   "unicodeName": "MATHEMATICAL RIGHT ANGLE BRACKET"
  },
  {
   "category": "Delimiters",
   "command": "lfloor",
   "glyph": "\u230a",
   "unicodeName": "LEFT FLOOR"
  },
  {
   "category": "Delimiters",
   "command": "rfloor",
   "glyph": "\u230b",
   "unicodeName": "RIGHT FLOOR"
  },
  {
   "category": "Delimiters",
   "command": "lceil",
   "glyph": "\u2308",
   "unicodeName": "LEFT CEILING"
  },
  {
   "category": "Delimiters",
   "command": "rceil",
   "glyph": "\u2309",
   "unicodeName": "RIGHT CEILING"
  },
  {
   "category": "Miscellaneous",
   "command": "ldots",
   "glyph": "\u2026",
   "unicodeName": "HORIZONTAL ELLIPSIS"
  },
  {
   "category": "Miscellaneous",
   "command": "dots",
   "glyph": "\u2026",
   "unicodeName": "HORIZONTAL ELLIPSIS"
  },
  {
   "category": "Miscellaneous",
   "command": "cdots",
   "glyph": "\u22ef",
   "unicodeName": "MIDLINE HORIZONTAL ELLIPSIS"
  },
  {
   "category": "Miscellaneous",
   "command": "vdots",
   "glyph": "\u22ee",
   "unicodeName": "VERTICAL ELLIPSIS"
  },
  {
   "category": "Miscellaneous",
   "command": "ddots",
   "glyph": "\u22f1",
   "unicodeName": "DOWN RIGHT DIAGONAL ELLIPSIS"
  },
  {
   "category": "Miscellaneous",
   "command": "ell",
   "glyph": "\u2113",
   "unicodeName": "SCRIPT SMALL L"
  },
  {
   "category": "Miscellaneous",
   "command": "hbar",
   "glyph": "\u210f",
   "unicodeName": "PLANCK CONSTANT OVER TWO PI"
  },
  {
   "category": "Miscellaneous",
   "command": "aleph",
   "glyph": "\u2135",
   "unicodeName": "ALEF SYMBOL"
  },
  {
   "category": "Miscellaneous",
   "command": "angle",
   "glyph": "\u2220",
   "unicodeName": "ANGLE"
  },
  {
   "category": "Miscellaneous",
   "command": "triangle",
   "glyph": "\u25b3",
   "unicodeName": "WHITE UP-POINTING TRIANGLE"
  },
  {
   "category": "Miscellaneous",
   "command": "square",
   "glyph": "\u25a1",
   "unicodeName": "WHITE SQUARE"
  },
  {
   "category": "Miscellaneous",
   "command": "dagger",
   "glyph": "\u2020",
   "unicodeName": "DAGGER"
  },
  {
   "category": "Miscellaneous",
   "command": "ddagger",
   "glyph": "\u2021",
   "unicodeName": "DOUBLE DAGGER"
  },
  {
   "category": "Miscellaneous",
   "command": "checkmark",
   "glyph": "\u2713",
   "unicodeName": "CHECK MARK"
  },
  {
   "category": "Miscellaneous",
   "command": "Re",
   "glyph": "\u211c",
   "unicodeName": "BLACK-LETTER CAPITAL R"
  },
  {
   "category": "Miscellaneous",
   "command": "Im",
   "glyph": "\u2111",
   "unicodeName": "BLACK-LETTER CAPITAL I"
  },
  {
   "category": "Miscellaneous",
   "command": "wp",
   "glyph": "\u2118",
   "unicodeName": "SCRIPT CAPITAL P"
  },
  {
   "category": "Miscellaneous",
   "command": "imath",
   "glyph": "\u0131",
   "unicodeName": "LATIN SMALL LETTER DOTLESS I"
  },
  {
   "category": "Miscellaneous",
   "command": "jmath",
   "glyph": "\u0237",
   "unicodeName": "LATIN SMALL LETTER DOTLESS J"
  }
 ],
 "escapedLiterals": {
  "#": "#",
  "$": "$",
  "%": "%",
  "&": "&",
  "_": "_",
  "{": "{",
  "}": "}"
 },
 "fractionSlash": "\u2044",
 "operators": {
  "Pr": "Pr",
  "arccos": "arccos",
  "arcsin": "arcsin",
  "arctan": "arctan",
  "arg": "arg",
  "bmod": "mod",
  "cos": "cos",
  "cosh": "cosh",
  "cot": "cot",
  "coth": "coth",
  "csc": "csc",
  "deg": "deg",
  "det": "det",
  "dim": "dim",
  "exp": "exp",
  "gcd": "gcd",
  "hom": "hom",
  "inf": "inf",
  "ker": "ker",
  "lg": "lg",
  "lim": "lim",
  "liminf": "liminf",
  "limsup": "limsup",
  "ln": "ln",
  "log": "log",
  "max": "max",
  "min": "min",
  "sec": "sec",
  "sin": "sin",
  "sinh": "sinh",
  "sup": "sup",
  "tan": "tan",
  "tanh": "tanh"
 },
 "radicals": {
  "2": "\u221a",
  "3": "\u221b",
  "4": "\u221c"
 },
 "subscripts": {
  "(": "\u208d",
  ")": "\u208e",
  "+": "\u208a",
  "-": "\u208b",
  "0": "\u2080",
  "1": "\u2081",
  "2": "\u2082",
  "3": "\u2083",
  "4": "\u2084",
  "5": "\u2085",
  "6": "\u2086",
  "7": "\u2087",
  "8": "\u2088",
  "9": "\u2089",
  "=": "\u208c",
  "a": "\u2090",
  "e": "\u2091",
  "h": "\u2095",
  "i": "\u1d62",
  "j": "\u2c7c",
  "k": "\u2096",
  "l": "\u2097",
  "m": "\u2098",
  "n": "\u2099",
  "o": "\u2092",
  "p": "\u209a",
  "r": "\u1d63",
  "s": "\u209b",
  "t": "\u209c",
  "u": "\u1d64",
  "v": "\u1d65",
  "x": "\u2093"
 },
 "superscripts": {
  "(": "\u207d",
  ")": "\u207e",
  "+": "\u207a",
  "-": "\u207b",
  "0": "\u2070",
  "1": "\u00b9",
  "2": "\u00b2",
  "3": "\u00b3",
  "4": "\u2074",
  "5": "\u2075",
  "6": "\u2076",
  "7": "\u2077",
  "8": "\u2078",
  "9": "\u2079",
  "=": "\u207c",
  "a": "\u1d43",
  "b": "\u1d47",
  "c": "\u1d9c",
  "d": "\u1d48",
  "e": "\u1d49",
  "f": "\u1da0",
  "g": "\u1d4d",
  "h": "\u02b0",
  "i": "\u2071",
  "j": "\u02b2",
  "k": "\u1d4f",
  "l": "\u02e1",
  "m": "\u1d50",
  "n": "\u207f",
  "o": "\u1d52",
  "p": "\u1d56",
  "r": "\u02b3",
  "s": "\u02e2",
  "t": "\u1d57",
  "u": "\u1d58",
  "v": "\u1d5b",
  "w": "\u02b7",
  "x": "\u02e3",
  "y": "\u02b8",
  "z": "\u1dbb"
 },
 "symbolReasons": {
  " ": "Spacing commands are typographic adjustments with no plain-text equivalent.",
  "!": "Spacing commands such as \\! are typographic adjustments with no plain-text equivalent.",
  ",": "Spacing commands such as \\, are typographic adjustments with no plain-text equivalent.",
  ":": "Spacing commands such as \\: are typographic adjustments with no plain-text equivalent.",
  ";": "Spacing commands such as \\; are typographic adjustments with no plain-text equivalent.",
  "\\": "A line break has no inline form \u2014 the replacement has to stay on one line."
 },
 "unsupportedReasons": {
  "acute": "An accent cannot be drawn over other characters in plain text.",
  "atop": "\\atop needs two-dimensional layout, which has no inline Unicode form.",
  "bar": "An accent cannot be drawn over other characters in plain text.",
  "boldsymbol": "Bold, script and fraktur alphabets are not supported yet.",
  "breve": "An accent cannot be drawn over other characters in plain text.",
  "cases": "The cases environment needs two-dimensional layout, which has no inline Unicode form.",
  "choose": "\\choose needs two-dimensional layout, which has no inline Unicode form. Try \\binom{n}{k}, which falls back to C(n, k).",
  "cite": "\\cite belongs to a LaTeX document, not to inline text.",
  "ddot": "An accent cannot be drawn over other characters in plain text.",
  "displaystyle": "\\displaystyle only affects typeset size; there is nothing to insert.",
  "dot": "An accent cannot be drawn over other characters in plain text.",
  "emph": "Italic alphabets are not supported yet.",
  "footnote": "\\footnote belongs to a LaTeX document, not to inline text.",
  "grave": "An accent cannot be drawn over other characters in plain text.",
  "hat": "An accent cannot be drawn over other characters in plain text.",
  "hspace": "Spacing commands are typographic adjustments with no plain-text equivalent.",
  "label": "\\label belongs to a LaTeX document, not to inline text.",
  "limits": "\\limits only affects typeset placement; there is nothing to insert.",
  "mathbf": "Bold, script and fraktur alphabets are not supported yet.",
  "mathcal": "Bold, script and fraktur alphabets are not supported yet.",
  "mathfrak": "Bold, script and fraktur alphabets are not supported yet.",
  "mathit": "Italic alphabets are not supported yet.",
  "mathring": "An accent cannot be drawn over other characters in plain text.",
  "mathscr": "Bold, script and fraktur alphabets are not supported yet.",
  "mathsf": "Sans-serif alphabets are not supported yet.",
  "mathtt": "Monospace alphabets are not supported yet.",
  "matrix": "A matrix needs two-dimensional layout, which has no inline Unicode form.",
  "nolimits": "\\nolimits only affects typeset placement; there is nothing to insert.",
  "over": "\\over needs two-dimensional layout, which has no inline Unicode form. Try \\frac{a}{b}, which falls back to a/b.",
  "overbrace": "An overbrace cannot be drawn over other characters in plain text.",
  "overleftarrow": "An arrow cannot be drawn over other characters in plain text.",
  "overline": "An overline cannot be drawn over other characters in plain text.",
  "overrightarrow": "An arrow cannot be drawn over other characters in plain text.",
  "phantom": "\\phantom reserves typeset space; there is nothing to insert.",
  "qquad": "Spacing commands are typographic adjustments with no plain-text equivalent.",
  "quad": "Spacing commands are typographic adjustments with no plain-text equivalent.",
  "ref": "\\ref belongs to a LaTeX document, not to inline text.",
  "stackrel": "\\stackrel needs two-dimensional layout, which has no inline Unicode form.",
  "substack": "\\substack needs two-dimensional layout, which has no inline Unicode form.",
  "textbf": "Bold, script and fraktur alphabets are not supported yet.",
  "textit": "Italic alphabets are not supported yet.",
  "textstyle": "\\textstyle only affects typeset size; there is nothing to insert.",
  "tilde": "An accent cannot be drawn over other characters in plain text.",
  "underbrace": "An underbrace cannot be drawn over other characters in plain text.",
  "underline": "An underline cannot be drawn over other characters in plain text.",
  "vec": "An accent cannot be drawn over other characters in plain text.",
  "vspace": "Spacing commands are typographic adjustments with no plain-text equivalent.",
  "widehat": "An accent cannot be drawn over other characters in plain text.",
  "widetilde": "An accent cannot be drawn over other characters in plain text."
 },
 "vulgarFractions": {
  "0/3": "\u2189",
  "1/10": "\u2152",
  "1/2": "\u00bd",
  "1/3": "\u2153",
  "1/4": "\u00bc",
  "1/5": "\u2155",
  "1/6": "\u2159",
  "1/7": "\u2150",
  "1/8": "\u215b",
  "1/9": "\u2151",
  "2/3": "\u2154",
  "2/5": "\u2156",
  "3/4": "\u00be",
  "3/5": "\u2157",
  "3/8": "\u215c",
  "4/5": "\u2158",
  "5/6": "\u215a",
  "5/8": "\u215d",
  "7/8": "\u215e"
 }
};
